### ISSUE TITLE
Ability to store and query by a last modified field

### ISSUE THREAD

**Issue by krconv** [FundacionParaguaya/FP-PSP-SERVER#134]
*Feature Request*
In the mobile platform, we are currently forced to sync the entire database (all active families and all of their snapshots, along with all of the surveys) because there is no way to query by last-modified.

*Proposal*: 
Creation changes:
 - Add a "last-modified" field to families and surveys
 - Update this "last-modified" field anytime a family is modified (a new snapshot is created, a new priority is created, or the family itself is changed) or a survey is modified
 - Set this "last-modified" on any newly created family or survey

Query changes:
 - Add a GET parameter to the `/families` and `/surveys` parameters, e.g. `/api/v1/families?last_modified_gt=2018-02-20T15:03:05` (in UTC time zone)
 - Use this GET parameter using JPA to the family and survey services

**Comment by rodrigojv** [comment]
@krconv the new endpoint changes are available on the testing server:
https://testing.backend.povertystoplight.org/
