### ISSUE TITLE
Estimated date format for priority is not the same for both setting and getting

### ISSUE THREAD

**Issue by krconv** [FundacionParaguaya/FP-PSP-SERVER#137]
https://github.com/FundacionParaguaya/FP-PSP-SERVER/blob/bf2a083c73cf350ef406f6f0a455208f971b8f5d/src/main/java/py/org/fundacionparaguaya/pspserver/surveys/entities/SnapshotIndicatorPriorityEntity.java#L117

Currently, the API requires a date of the format `dd/MM/yyyy` in the POST request for priorities, where the GET request for priorities will return a date of the format `yyyy-MM-dd`. 

```java
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
return estimatedDate.format(formatter);
```

Not a big deal, but wanted to point it out!

**Comment by rodrigojv** [comment]
Thank you for pointing that out @krconv. We will take a look at it.

**Comment by rodrigojv** [comment]
We have verified and this behaviour is actually correct.
