### ISSUE TITLE
Incorrect URL for image uploading

### ISSUE THREAD

**Issue by krconv** [FundacionParaguaya/FP-PSP-SERVER#160]
I believe that the start of the image URL should be `https://s3.` instead of `https://s3-`. This causes clients using these uploaded images (not the survey images) to receive an unknown domain name error. The related line is below:

https://github.com/FundacionParaguaya/FP-PSP-SERVER/blob/bf2a083c73cf350ef406f6f0a455208f971b8f5d/src/main/java/py/org/fundacionparaguaya/pspserver/system/services/impl/ImageUploadServiceImpl.java#L61

**Comment by carlosbflores** [comment]
@krconv I checked the URLs generated by AWS and by the Service, you're right, `https://s3.` is the correct format, although both URLs seems to be working fine in the web app, will talk to @rodrigojv and change that.

**Comment by carlosbflores** [comment]
This issue has been fixed

**Comment by rodrigojv** [comment]
Thank you @carlosbflores , will close this issue.
