### ISSUE TITLE
Newly created families are not automatically assigned to its creator

### ISSUE THREAD

**Issue by krconv** [FundacionParaguaya/FP-PSP-SERVER#173]
It seems that when a new family is created, it is not automatically associated with the user that took the first snapshot for it. I don't know if this behavior is intended, so I wanted to bring it up in case it isn't!

For example, `colombia_survey_user` created a family named Ben Hylak (id: `45`). This family was properly created on the server, but the new family does not show up when endpoint `api/v1/families` is queried with `colombia_survey_user`.

Not sure how this affects the web front end. The android front end will remember the newly created family until the user logs out, at which point the family is no longer accessible.

**Comment by rodrigojv** [comment]
Thank you @krconv for bringing this to our attention. We will check this behaviour to make sure it is the intended.
