### ISSUE TITLE
Display snapshots indicators in a map

### ISSUE THREAD

**Issue by rodrigojv** [FundacionParaguaya/FP-PSP-SERVER#54]
Snapshots are instances of surveys. 

Each snapshot, when stored, should have information about the location of the person interviewed. This information will be latitude and longitude coordinates stored in the snapshots_indicators table.

The idea of this feature is to take such location information for a set of snapshots and display them as points in a Google Map. This map will be displayed in the front-end, and should have the following filters:

1. **Country selector** : to obtain all families of that country
2. **City selector:** to obtain all families of that city
3. **Hub**: the Hub that the family should belong to
4. **Organization**: the Organization that the family should belong to
5. **Partner**: the Partner that the familiy should belong to
6. **Indicator**: to select a specific indicator field. This is a field of the `data_collect.snapshots_indicators` (i.e. the table where snapshots of type indicators are stored)
7. **Color**: red, yellow or green. These are values for the `snapshots_indicators` fields.

**Basic Flow**
1. The user access a page with the filters above mentioned available
2. The user selects one or more filters and hits a Search button
3. A request to the server is triggered and a set of GPS points are retrieved in a JSON format.
4. The front-end displays the JSON in a Google Map

**Developer notes:**
1. Snapshots when stored are related to family entities by way of the `data_collect.snapshots_economics.familiy_id` column.
2. Partner, Hub and Organization can be obtained by the relationship that the `ps_families.familiy` table has with the  #`ps_network.application` table.

**Comment by krconv** [comment]
Is this along the lines of what you are looking for?
![](https://drive.google.com/uc?export=download&id=1I4cwcWiSSIFoIiPpKI64TKJL0zbL6ptT)

**Comment by rodrigojv** [comment]
Yes it is! Looks very close to what we're looking for.

One thing to keep in mind is how many points to show on the map. For example if Paraguay has 5 green, 4 red and 3 yellow. From a 'zomed out' perspective, we can show one point for each color with the number inside of each point. Then when you zoom in on the country we can show all of the points for each color.

**Comment by bhylak** [comment]
@krconv want to close this issue?

**Comment by pA1nD** [comment]
Tracking this now in FundacionParaguaya/fp-psp-frontend#199
